### ISSUE TITLE
Occured error in test train_dynamics.py

### ISSUE THREAD

**Issue by romiet-jin** [quantumiracle/UPESI#1]
Hi
I'm studying with your code
When collecting training and testing dataset, the following error occurs.

ModuleNotFoundError: No module named 'robosuite.class_wrappers'

I hope to know how to solve it

Thank you :)

**Comment by quantumiracle** [comment]
Hi, 
I'm not sure which version of robosuite are you using. But I guess this is the problem. We use a previous version of robosuite, which can be found [here](https://github.com/quantumiracle/Robotic_Door_Opening_with_Tactile_Simulation). You can follow the installation process in that repo to get robosuite (actually we name our local version robolite). Specifically, you can follow these lines in the installation step:
![image](https://user-images.githubusercontent.com/22659010/147391066-a3567484-8dd5-4324-b190-998fffcef3bd.png)

**Comment by romiet-jin** [comment]
Thanks for answering :)
I used 1.3.0 version.
downloaded robosuite from the site you gave, but the same error occurs.
Is there anything else I should check?

**Comment by quantumiracle** [comment]
Could you please check if there is this `class_wrappers` folder in your robosuite wrapper? If not, maybe just copy [this one](https://github.com/quantumiracle/Robotic_Door_Opening_with_Tactile_Simulation/tree/master/environment/robolite/robosuite) and paste it in your robosuite and reinstall it. Be sure to install robosuite with `pip install -e .` rather than `pip install robosuite`, also uninstall the previous one before you install the one containing the `class_wrappers` folder.

**Comment by romiet-jin** [comment]
Thanks for the advise.

I reinstalled and checked there is `class_wrappers` folder, and one `__init__` file in the folder.
![image](https://user-images.githubusercontent.com/62049960/147431532-f48356a8-af43-4b3f-a26a-7537d3455c9a.png)


but there is no 'latent_dynamics_provider'
What should i do in this case?
